logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[consul]
  watch = true
  prefix = "traefik"

[consulCatalog]
  domain = "consul.localhost"
  prefix = "traefik-consul"

[web]
  address = ":8080"